source_schema: Core_Schema_v1.sql
target_schema: Phys_Schema_v1.sql

#----------------------------------------------------------------------------------------#
#                          TABLE-LEVEL COLUMN -> FORMULA MAPPINGS 

#                                       WALL TABLES
#----------------------------------------------------------------------------------------#
Wall_Geometry:
  pk: Product_ID
  columns:
    total_height_mm:
      formula: total_height_mm
      args: [ Coords_XYZ ]
    total_length_mm:
      formula: total_length_mm
      args: [ Coords_XYZ ]
    total_thickness_mm:
      formula: total_thickness_mm
      args: [ Coords_XYZ]
    density_kgm3:
      formula: density_kgm3
      args: [ Concrete_Type ]
    element_volume_m3:
      formula: element_volume_m3
      args: [ Coords_XYZ, corb_volume_m3, void_volume_m3, Has_Corbel, Has_Void ]
    element_mass_kg:
      formula: element_mass_kg
      args: [ element_volume_m3, density_kgm3 ]

Wall_Zone_Geometry:
  pk: Zone_ID
  columns:
    zone_height_mm:
      formula: zone_height_mm
      args: [ Zone_Coords, Zone_Plane, total_height_mm ]
    zone_length_mm:
      formula: zone_length_mm
      args: [ Zone_Coords, Zone_Plane, total_length_mm ]
    zone_thickness_mm:
      formula: zone_width_mm
      args: [Zone_Coords, Zone_Plane, total_thickness_mm ]

Corbel_Geometry:
  pk: Corbel_ID
  columns:
    depth_mm:
      formula: corb_depth_mm
      args: [ Corb_Coords_XYZ ]
    length_mm:
      formula: corb_length_mm
      args: [ Corb_Coords_XYZ, Extruded_Plane ]
    midpoint_mm:
      formula: corb_midpoint_mm
      args: [ Corb_Coords_XYZ, Extruded_Plane ]
    dist_from_top_mm:
      formula: corb_dist_from_top_mm
      args: [ Coords_XYZ, Corb_Coords_XYZ ]
    rect_blk_height_mm:
      formula: rect_blk_height_mm
      args: [ Corb_Coords_XYZ ]
    tri_blk_height_mm:
      formula: tri_blk_height_mm
      args: [ Corb_Coords_XYZ ]
    center_h_offset_mm:
      formula: centerHoffset_mm
      args: [ midpoint_mm, total_length_mm ]
    volume_m3:
      formula: corb_volume_m3
      args: [ depth_mm, length_mm, rect_blk_height_mm, tri_blk_height_mm ]
    mass_kg:
      formula: corb_mass_kg
      args: [ volume_m3, density_kgm3]

Wall_Voids:                         
  pk: Void_ID
  columns:
    base_v_offset_mm:
      formula: baseVoffset_mm
      args: [ Void_Coords_XYZ ]
    void_center_mm:
      formula: void_center_mm
      args: [ Void_Coords_XYZ ]
    center_h_offset_mm:
      formula: centerHoffset_mm
      args: [ void_center_mm, total_length_mm ]
    height_mm:
      formula: void_height_mm
      args: [ Void_Coords_XYZ ]
    length_mm:
      formula: void_length_mm
      args: [ Void_Coords_XYZ ]
    depth_mm:
      formula: void_depth_mm
      args: [ Void_Coords_XYZ ]
    volume_m3:
      formula: void_volume_m3
      args: [ length_mm, depth_mm, height_mm ]

Additional_Panelling:
  pk: Product_ID
  columns:
    panel_height_mm:
      formula: total_height_mm
      args: [ Panel_Coords_XYZ ]
    panel_length_mm:
      formula: total_length_mm
      args: [ Panel_Coords_XYZ ]
    panel_thickness_mm:
      formula: total_thickness_mm
      args: [ Panel_Coords_XYZ ]
    panel_volume_m3:
      formula: extra_layer_volume_m3
      args: [ panel_length_mm, panel_thickness_mm, panel_height_mm ]
    insul_height_mm:
      formula: total_height_mm
      args: [ Insul_Coords_XYZ ]
    insul_length_mm:
      formula: total_length_mm
      args: [ Insul_Coords_XYZ ]
    insul_thickness_mm:
      formula: total_thickness_mm
      args: [ Insul_Coords_XYZ ]
    insul_volume_m3:
      formula: extra_layer_volume_m3
      args: [ insul_length_mm, insul_thickness_mm, insul_height_mm ]

Wall_Long_Reinf:                            
  pk: Long_ID
  columns:
    bar_length_mm:
      formula: bar_length_mm
      args: [ Layer_Coords, Zone_Plane ]
    bar_area_mm2:
      formula: bar_area_mm2
      args: [ Bar_Diameter, Num_Bars ]
    effective_depth_mm:
      formula: effective_depth_mm
      args: [ Layer_Coords, Zone_Plane, zone_height_mm ]

Wall_Transv_Reinf:
  pk: Transv_ID
  columns:
    num_legs:
      formula: num_legs
      args: [ Shape_Coords, Bent_Plane ]
    volumetric_ratio_mm3:
      formula: volumetric_ratio_mm3
      args: [ Shape_Coords, Bent_Plane, Bar_Diameter, Spacing, zone_width_mm ]


#----------------------------------------------------------------------------------------#
#                                       BEAM TABLES                                      #
#----------------------------------------------------------------------------------------#
Beam_Geometry:
  pk: Product_ID
  columns:
    total_height_mm:
      formula: total_height_mm
      args: [ Coords_XYZ ]
    total_length_mm:
      formula: total_length_mm
      args: [ Coords_XYZ ]
    total_width_mm:
      formula: total_width_mm
      args: [ Coords_XYZ ]
    density_kgm3:
      formula: density_kgm3
      args: [ Concrete_Type ]
    element_volume_m3:
      formula: element_volume_m3
      args: [ Coords_XYZ, corb_volume_m3, Has_Corbel ]
    element_mass_kg:
      formula: element_mass_kg
      args: [ element_volume_m3, density_kgm3 ]

Beam_Zone_Geometry:
  pk: Zone_ID
  columns:
    zone_length_mm:
      formula: zone_length_mm
      args: [ Zone_Coords, Zone_Plane, total_length_mm ]
    zone_height_mm:
      formula: zone_height_mm
      args: [ Zone_Coords, Zone_Plane, total_height_mm ]
    zone_width_mm:
      formula: zone_width_mm
      args: [Zone_Coords, Zone_Plane, total_width_mm ]

Beam_Long_Reinf:                            
  pk: Long_ID
  columns:
    bar_length_mm:
      formula: bar_length_mm
      args: [ Layer_Coords, Zone_Plane ]
    bar_area_mm2:
      formula: bar_area_mm2
      args: [ Bar_Diameter, Num_Bars ]
    effective_depth_mm:
      formula: effective_depth_mm
      args: [ Layer_Coords, Zone_Plane, zone_height_mm ]

Beam_Transv_Reinf:
  pk: Transv_ID
  columns:
    num_legs:
      formula: num_legs
      args: [ Shape_Coords, Bent_Plane ]
    volumetric_ratio_mm3:
      formula: volumetric_ratio_mm3
      args: [ Shape_Coords, Bent_Plane, Bar_Diameter, Spacing, zone_width_mm ]


#----------------------------------------------------------------------------------------#
#                                     COLUMN TABLES                                      #
#----------------------------------------------------------------------------------------#
Column_Geometry:
  pk: Product_ID
  columns:
    total_height_mm:
      formula: total_height_mm
      args: [ Coords_XYZ ]
    total_depth_mm:
      formula: total_length_mm
      args: [ Coords_XYZ ]
    total_width_mm:
      formula: total_width_mm
      args: [ Coords_XYZ ]
    diameter_a_mm:
      formula: d_a_mm
      args: [ Coords_XYZ ]
    diameter_b_mm:
      formula: d_b_mm
      args: [ Coords_XYZ ]
    density_kgm3:
      formula: density_kgm3
      args: [ Concrete_Type ]
    element_volume_m3:
      formula: element_volume_m3
      args: [ Coords_XYZ, corb_volume_m3, Has_Corbel ]
    element_mass_kg:
      formula: element_mass_kg
      args: [ element_volume_m3, density_kgm3 ]

Column_Zone_Geometry:
  pk: Zone_ID
  columns:
    zone_length_mm:
      formula: zone_length_mm
      args: [ Zone_Coords, Zone_Plane, total_length_mm ]
    zone_height_mm:
      formula: zone_height_mm
      args: [ Zone_Coords, Zone_Plane, total_height_mm ]
    zone_width_mm:
      formula: zone_width_mm
      args: [Zone_Coords, Zone_Plane, total_width_mm ]

Column_Long_Reinf:                            
  pk: Long_ID
  columns:
    bar_length_mm:
      formula: bar_length_mm
      args: [ Layer_Coords, Zone_Plane ]
    bar_area_mm2:
      formula: bar_area_mm2
      args: [ Bar_Diameter, Num_Bars ]
    effective_depth_mm:
      formula: effective_depth_mm
      args: [ Layer_Coords, Zone_Plane, zone_height_mm ]

Column_Transv_Reinf:
  pk: Transv_ID
  columns:
    num_legs:
      formula: num_legs
      args: [ Shape_Coords, Bent_Plane ]
    volumetric_ratio_mm3:
      formula: volumetric_ratio_mm3
      args: [ Shape_Coords, Bent_Plane, Cross-Section, Bar_Diameter, Spacing, zone_width_mm, diameter_a_mm, diameter_b_mm ]


#----------------------------------------------------------------------------------------#
#                                 SOLID SLAB TABLES                                      #
#----------------------------------------------------------------------------------------#
Slab_Geometry:
  pk: Product_ID
  columns:
    total_height_mm:
      formula: total_height_mm
      args: [ Coords_XYZ ]
    total_length_mm:
      formula: total_length_mm
      args: [ Coords_XYZ ]
    total_width_mm:
      formula: total_width_mm
      args: [ Coords_XYZ ]
    density_kgm3:
      formula: density_kgm3
      args: [ Concrete_Type ]
    element_volume_m3:
      formula: element_volume_m3
      args: [ Coords_XYZ, void_volume_m3, Has_Void ]
    element_mass_kg:
      formula: element_mass_kg
      args: [ element_volume_m3, density_kgm3 ]

Slab_Zone_Geometry:
  pk: Zone_ID
  columns:
    zone_length_mm:
      formula: zone_length_mm
      args: [ Zone_Coords, Zone_Plane, total_length_mm ]
    zone_height_mm:
      formula: zone_height_mm
      args: [ Zone_Coords, Zone_Plane, total_height_mm ]
    zone_thickness_mm:
      formula: zone_width_mm
      args: [Zone_Coords, Zone_Plane, total_thickness_mm ]

Slab_Voids:                         
  pk: Void_ID
  columns:
    base_v_offset_mm:
      formula: baseVoffset_mm
      args: [ Void_Coords_XYZ ]
    void_center_mm:
      formula: void_center_mm
      args: [ Void_Coords_XYZ ]
    center_h_offset_mm:
      formula: centerHoffset_mm
      args: [ void_center_mm, total_length_mm ]
    height_mm:
      formula: void_height_mm
      args: [ Void_Coords_XYZ ]
    length_mm:
      formula: void_length_mm
      args: [ Void_Coords_XYZ ]
    depth_mm:
      formula: void_depth_mm
      args: [ Void_Coords_XYZ ]
    volume_m3:
      formula: void_volume_m3
      args: [ void_length_mm, void_depth_mm, void_height_mm ]

Slab_Long_Reinf:                            
  pk: Long_ID
  columns:
    bar_length_mm:
      formula: bar_length_mm
      args: [ Layer_Coords, Zone_Plane ]
    bar_area_mm2:
      formula: bar_area_mm2
      args: [ Bar_Diameter, Num_Bars ]
    effective_depth_mm:
      formula: effective_depth_mm
      args: [ Layer_Coords, Zone_Plane, zone_height_mm ]

Slab_Transv_Reinf:
  pk: Transv_ID
  columns:
    num_legs:
      formula: num_legs
      args: [ Shape_Coords, Bent_Plane ]
    volumetric_ratio_mm3:
      formula: volumetric_ratio_mm3
      args: [ Shape_Coords, Bent_Plane, Bar_Diameter, Spacing, zone_width_mm ]



#----------------------------------------------------------------------------------------#
#                                       HCS TABLES                                       #
#----------------------------------------------------------------------------------------#
HCS_Prestressing:
  pk: Strand_ID
  columns:
    tendon_area_mm2:
      formula: tendon_area_mm2
      args: [ Strand_Diameter, Num_Wires ]
    effective_depth_mm:
      formula: tendon_eff_depth_mm
      args: [ Strand_Coord_XY, Height ]